let manifest = [
    {
        src:"spritesheet.js",
        id:"spritesheet"
    },
    {
        src:"lib/fire.wav",
        id:"fireSound",
        data:4
    },
    {
        src:"lib/playerHurt.wav",
        id:"playerHurtSound",
        data:4
    },
    {
        src:"lib/playerDead.wav",
        id:"playerDeadSound",
        data:4
    },
    {
        src:"lib/bulletHit.wav",
        id:"bulletHitSound",
        data:4
    },
    {
        src:"lib/circleSpawn.wav",
        id:"circleSpawnSound",
        data:4
    },
    {
        src:"lib/circleDead.wav",
        id:"circleDeadSound",
        data:4
    },
    {
        src:"lib/squareSpawn.wav",
        id:"squareSpawnSound",
        data:4
    },
    {
        src:"lib/starSpawn.wav",
        id:"starSpawnSound",
        data:4
    },
    {
        src:"lib/starDead.wav",
        id:"starDeadSound",
        data:4
    },
    {
        src:"lib/rectangleSpawn.wav",
        id:"rectangleSpawnSound",
        data:4
    },
    {
        src:"lib/hexagonSpawn.wav",
        id:"hexagonSpawnSound",
        data:4
    },
    {
        src:"lib/hexagonDead.wav",
        id:"hexagonDeadSound",
        data:4
    }
];